- name: set apache package name for debian
  set_fact:
    apache_package_name: apache2

- name: set apache package name for RedHat
  set_fact:
    apache_package_name: httpd
  when: ansible_os_family == "RedHat"
  

# - include: debian.yml
#   become: true
#   when: ansible_os_family == "Debian"

# - include: redhat.yml
#   become: true
#   when: ansible_os_family == "RedHat"

- name: install apache package
  become: true
  package:
    name: '{{ apache_package_name }}'
    state: present

- name: Check if Apache HTTP Service is Up
  become: true
  systemd:
    name: '{{ apache_package_name }}'
    state: started
    enabled: yes
    daemon_reload: yes