all:
  hosts:
    ubuntu:
  children:
    webservers:
      hosts:
        ubuntu:
        # debian:
    dbservers:
      hosts:
        centos:
    vagrant:
      hosts:
        # debian:
        ubuntu:
        centos: