- name: Install mysql
  hosts: dbservers
  become: true
  vars:
    mariadb_version: 10.2

  tasks:
    - name: install mariadb packages for debian family
      apt:
          name: 
          - software-properties-common
          state: present
          update_cache: yes
          cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: add mariadb repo
      apt_repository:
          repo: 'deb [arch=amd64,arm64,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.3/ubuntu {{ ansible_distribution_release }} main'
          name: mariadb
          state: present
      when: ansible_os_family == "Debian"

    - name: install mariadb packages for debian family
      apt:
          name: 
          - mariadb-server
          - mariadb-client
          state: present
          update_cache: yes
      when: ansible_os_family == "Debian"

    - name: install MariaDB packages for RedHat family - REPO
      template:
        src: templates/redhat.repo.j2
        dest: /etc/yum.repos.d/MariaDB.repo
      when: ansible_os_family == "RedHat"
      
    - name: install MariaDB packages for RedHat family - INSTALL
      yum:
        name: 
        - MariaDB-server
        - MariaDB-client
        state: present
      when: ansible_os_family == "RedHat"

    # va redémarrer MariaDB à chaque fois
    - name: restart MariaDB
      systemd:
        name: mariadb
        state: restarted
        daemon_reload: yes
    
    
