---
# tasks file for mariadb
- include: install.yml
  become: true
  tags: 
   - install
   - update

- name: Check if Mariadb Service is Up
  become: true
  systemd:
    name: mariadb
    state: started
    enabled: yes
    daemon_reload: yes