- name: install MariaDB packages for RedHat family - REPO
  template:
    src: redhat.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
  

- name: install MariaDB packages for RedHat family - INSTALL
  yum:
    name: 
     - mariadb-server
    state: present
  notify: restart MariaDB
