- name: install basic packages for debian family
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  register: install_packages

# - name: debug
#   debug:
#     msg: "{{ install_packages.stdout_lines }}"

- block:
  - name: install basic packages for RedHat family - REPOS
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      state: present

  - name: install basic packages for RedHat family - INSTALL
    yum:
      name: "{{ packages }}"
      state: present
  when: ansible_os_family == "RedHat"
  

