- name: install basic packages for RedHat family - REPOS
  yum:
    name: epel-release
    state: present

- name: install basic packages for RedHat family - INSTALL
  yum:
    name: "{{ packages }}"
    state: present
